
-- =========================================================================
-- Revenue Targets Phase 1 CORRECTION
-- Enforces Full-Day roll-up-only benchmark; forbids service-period duplication.
-- =========================================================================

-- 1) Add is_rollup_only to venue_service_periods
ALTER TABLE public.venue_service_periods
  ADD COLUMN IF NOT EXISTS is_rollup_only boolean NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS vsp_rollup_idx
  ON public.venue_service_periods(venue_id) WHERE is_rollup_only = true;

COMMENT ON COLUMN public.venue_service_periods.is_rollup_only IS
  'When true, this period is a benchmark/roll-up container only. It must be excluded from operational Manager target creation, operational sums, and event totals. Used to attach Full-Day Statistical benchmarks for multi-period venues without duplicating operational periods.';

-- 2) Corrective cleanup of fabricated Statistical rows generated by the
--    prior v2 behaviour that duplicated Full-Day medians into every
--    configured service period. A fabricated row is one whose service
--    period is NOT the venue's Full-Day benchmark AND was created by the
--    v2 model_version. Manager rows are NEVER touched.
DO $mig$
DECLARE
  v_deleted integer := 0;
BEGIN
  WITH bench AS (
    SELECT sp.venue_id,
           (
             SELECT sp2.id FROM public.venue_service_periods sp2
              WHERE sp2.venue_id = sp.venue_id AND sp2.is_active
                AND (
                  sp2.is_rollup_only
                  OR (
                    lower(sp2.name) = 'full day'
                    AND NOT EXISTS (
                      SELECT 1 FROM public.venue_service_periods sp3
                       WHERE sp3.venue_id = sp.venue_id AND sp3.is_active
                         AND NOT sp3.is_rollup_only
                         AND lower(sp3.name) <> 'full day'
                    )
                  )
                )
              ORDER BY sp2.is_rollup_only DESC
              LIMIT 1
           ) AS bench_period_id
      FROM public.venue_service_periods sp
     GROUP BY sp.venue_id
  ), del AS (
    DELETE FROM public.revenue_statistical_targets_daily d
     USING bench b
     WHERE d.venue_id = b.venue_id
       AND d.model_version IN ('same_weekday_service_period_median_12w_v1')
       AND (b.bench_period_id IS NULL OR d.service_period_id IS DISTINCT FROM b.bench_period_id)
    RETURNING d.id
  )
  SELECT COUNT(*) INTO v_deleted FROM del;

  RAISE NOTICE 'Corrective cleanup: removed % fabricated statistical rows', v_deleted;
END $mig$;

-- 3) Rewrite generate_revenue_statistical_targets_month_v2
CREATE OR REPLACE FUNCTION public.generate_revenue_statistical_targets_month_v2(
  p_tenant_id uuid, p_year integer, p_month integer,
  p_venue_ids uuid[], p_model_version text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_month_start date;
  v_month_end date;
  v_lookback_start date;
  v_lookback_end date;
  v_inserted integer := 0;
  v_monthly_total numeric := 0;
  v_venue_totals jsonb := '{}'::jsonb;
  v_model_label text := 'Same Weekday Median — 12 Weeks (Full-Day Roll-up)';
  v_model_version text := 'same_weekday_full_day_median_12w_v3';
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  IF NOT (public.is_super_admin(v_uid) OR public.is_tenant_member(p_tenant_id, v_uid)) THEN
    RAISE EXCEPTION 'Not authorized for tenant';
  END IF;
  IF NOT (public.is_super_admin(v_uid)
          OR public.has_role(v_uid,'admin'::public.app_role)
          OR public.has_role(v_uid,'manager'::public.app_role)) THEN
    RAISE EXCEPTION 'Not authorized: manager or admin role required';
  END IF;
  IF p_year < 2000 OR p_year > 2100 OR p_month < 1 OR p_month > 12 THEN
    RAISE EXCEPTION 'Invalid year/month';
  END IF;
  IF p_venue_ids IS NULL OR array_length(p_venue_ids,1) IS NULL THEN
    RAISE EXCEPTION 'venue_ids required';
  END IF;
  IF p_model_version NOT IN (
    'same_weekday_service_period_median_12w_v1',
    'same_weekday_full_day_median_12w_v3'
  ) THEN
    RAISE EXCEPTION 'Unsupported model version';
  END IF;
  IF EXISTS (
    SELECT 1 FROM unnest(p_venue_ids) vid
     WHERE NOT EXISTS (SELECT 1 FROM public.venues v WHERE v.id = vid AND v.tenant_id = p_tenant_id)
  ) THEN
    RAISE EXCEPTION 'One or more venues do not belong to tenant';
  END IF;

  v_month_start := make_date(p_year, p_month, 1);
  v_month_end   := (v_month_start + INTERVAL '1 month - 1 day')::date;
  v_lookback_end   := v_month_start - 1;
  v_lookback_start := v_lookback_end - (12*7 - 1);

  -- Ensure a Full-Day roll-up benchmark period exists for multi-period venues
  -- (or venues that have no Full-Day period yet).
  INSERT INTO public.venue_service_periods
    (tenant_id, venue_id, name, code, start_time, end_time, crosses_midnight,
     applicable_weekdays, is_active, sort_order, effective_from,
     is_rollup_only, created_by, updated_by)
  SELECT p_tenant_id, v.id, 'Full Day (Benchmark)', 'FULL_DAY_ROLLUP',
         '00:00'::time, '23:59:59'::time, false,
         ARRAY[0,1,2,3,4,5,6]::smallint[], true, 0, '2000-01-01'::date,
         true, v_uid, v_uid
    FROM public.venues v
   WHERE v.id = ANY(p_venue_ids) AND v.tenant_id = p_tenant_id
     AND NOT EXISTS (
       SELECT 1 FROM public.venue_service_periods sp
        WHERE sp.venue_id = v.id AND sp.is_active AND sp.is_rollup_only
     )
     AND (
       -- multi-period, OR no Full-Day operational period
       (SELECT COUNT(*) FROM public.venue_service_periods sp
          WHERE sp.venue_id = v.id AND sp.is_active AND NOT sp.is_rollup_only) > 1
       OR NOT EXISTS (
         SELECT 1 FROM public.venue_service_periods sp
          WHERE sp.venue_id = v.id AND sp.is_active AND NOT sp.is_rollup_only
            AND lower(sp.name) = 'full day'
       )
     );

  -- Resolve the benchmark period per venue.
  CREATE TEMP TABLE tmp_bench ON COMMIT DROP AS
  SELECT v.id AS venue_id, v.name AS venue_name,
         COALESCE(
           (SELECT sp.id FROM public.venue_service_periods sp
             WHERE sp.venue_id = v.id AND sp.is_active AND sp.is_rollup_only
             ORDER BY sp.created_at LIMIT 1),
           (SELECT sp.id FROM public.venue_service_periods sp
             WHERE sp.venue_id = v.id AND sp.is_active AND NOT sp.is_rollup_only
               AND lower(sp.name) = 'full day'
               AND NOT EXISTS (
                 SELECT 1 FROM public.venue_service_periods sp2
                  WHERE sp2.venue_id = v.id AND sp2.is_active AND NOT sp2.is_rollup_only
                    AND lower(sp2.name) <> 'full day'
               )
             LIMIT 1)
         ) AS bench_period_id,
         COALESCE(
           (SELECT sp.name FROM public.venue_service_periods sp
             WHERE sp.venue_id = v.id AND sp.is_active AND sp.is_rollup_only
             ORDER BY sp.created_at LIMIT 1),
           (SELECT sp.name FROM public.venue_service_periods sp
             WHERE sp.venue_id = v.id AND sp.is_active AND NOT sp.is_rollup_only
               AND lower(sp.name) = 'full day'
             LIMIT 1)
         ) AS bench_period_name
    FROM public.venues v
   WHERE v.id = ANY(p_venue_ids) AND v.tenant_id = p_tenant_id;

  -- Historical daily totals from sales_records (venue+date grain).
  CREATE TEMP TABLE tmp_hist ON COMMIT DROP AS
  SELECT sr.venue_id, sr.date::date AS business_date,
         EXTRACT(DOW FROM sr.date::date)::int AS weekday,
         SUM(COALESCE(sr.total_sales,0))::numeric AS revenue,
         SUM(COALESCE(sr.guests,0))::numeric AS guests
    FROM public.sales_records sr
   WHERE sr.tenant_id = p_tenant_id
     AND sr.venue_id = ANY(p_venue_ids)
     AND sr.date::date BETWEEN v_lookback_start AND v_lookback_end
   GROUP BY sr.venue_id, sr.date::date;

  -- Stage exactly ONE row per (venue, date) attached to the benchmark period.
  CREATE TEMP TABLE tmp_stage ON COMMIT DROP AS
  SELECT p_tenant_id AS tenant_id,
         b.venue_id, b.venue_name,
         b.bench_period_id AS service_period_id,
         b.bench_period_name AS service_period_name,
         d::date AS target_date,
         EXTRACT(DOW FROM d)::int AS weekday
    FROM tmp_bench b
    CROSS JOIN LATERAL generate_series(v_month_start, v_month_end, INTERVAL '1 day') AS d
   WHERE b.bench_period_id IS NOT NULL;

  -- Atomic replace within scope: purge ANY stale rows for these venues/month
  -- (this catches previously-fabricated duplicated service-period rows too).
  DELETE FROM public.revenue_statistical_targets_daily d
   USING tmp_bench b
   WHERE d.tenant_id = p_tenant_id
     AND d.venue_id = b.venue_id
     AND d.target_date BETWEEN v_month_start AND v_month_end;

  INSERT INTO public.revenue_statistical_targets_daily (
    tenant_id, venue_id, venue_name_snapshot, service_period_id, service_period_name_snapshot,
    target_date, statistical_target_amount, statistical_guest_target, statistical_spend_per_guest,
    model, model_version, lookback_start, lookback_end,
    observation_count, revenue_observation_count, guest_observation_count,
    confidence, generated_by
  )
  SELECT s.tenant_id, s.venue_id, s.venue_name, s.service_period_id, s.service_period_name,
         s.target_date,
         COALESCE(round(agg.rev_median::numeric, 2), 0),
         agg.guest_median,
         CASE
           WHEN agg.guest_median IS NULL OR agg.guest_median = 0 THEN NULL
           ELSE round((agg.rev_median / agg.guest_median)::numeric, 2)
         END,
         v_model_label,
         v_model_version,
         v_lookback_start, v_lookback_end,
         COALESCE(agg.n,0), COALESCE(agg.n,0), COALESCE(agg.n_guests,0),
         CASE
           WHEN COALESCE(agg.n,0) = 0 THEN 'unavailable'
           WHEN COALESCE(agg.n,0) >= 4 THEN 'high'
           ELSE 'low'
         END,
         v_uid
    FROM tmp_stage s
    LEFT JOIN LATERAL (
      SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY h.revenue) AS rev_median,
             percentile_cont(0.5) WITHIN GROUP (ORDER BY NULLIF(h.guests,0)) AS guest_median,
             COUNT(*) AS n,
             COUNT(NULLIF(h.guests,0)) AS n_guests
        FROM tmp_hist h
       WHERE h.venue_id = s.venue_id AND h.weekday = s.weekday
    ) agg ON true;

  GET DIAGNOSTICS v_inserted = ROW_COUNT;

  SELECT COALESCE(SUM(statistical_target_amount),0)
    INTO v_monthly_total
    FROM public.revenue_statistical_targets_daily
   WHERE tenant_id = p_tenant_id AND venue_id = ANY(p_venue_ids)
     AND target_date BETWEEN v_month_start AND v_month_end;

  SELECT COALESCE(jsonb_object_agg(venue_id::text, total), '{}'::jsonb)
    INTO v_venue_totals
    FROM (SELECT venue_id, SUM(statistical_target_amount) AS total
            FROM public.revenue_statistical_targets_daily
           WHERE tenant_id = p_tenant_id AND venue_id = ANY(p_venue_ids)
             AND target_date BETWEEN v_month_start AND v_month_end
           GROUP BY venue_id) t;

  IF EXISTS (SELECT 1 FROM public.revenue_targets
              WHERE tenant_id=p_tenant_id AND year=p_year AND month=p_month) THEN
    UPDATE public.revenue_targets
       SET statistical_target_amount = v_monthly_total,
           statistical_model = v_model_label,
           statistical_generated_at = now()
     WHERE tenant_id=p_tenant_id AND year=p_year AND month=p_month;
  ELSE
    INSERT INTO public.revenue_targets(tenant_id,year,month,target_amount,venues,notes,created_by,
      statistical_target_amount, statistical_model, statistical_generated_at)
    VALUES (p_tenant_id,p_year,p_month,NULL,ARRAY[]::text[],'',v_uid,
      v_monthly_total, v_model_label, now());
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'inserted', v_inserted,
    'monthly_total', v_monthly_total,
    'venue_totals', v_venue_totals,
    'model', v_model_label,
    'model_version', v_model_version
  );
END
$function$;

-- 4) Rewrite ensure_revenue_manager_target_lines_month
--    - excludes is_rollup_only periods
--    - never seeds from statistical (leaves drivers blank)
--    - only inserts rows where reliable statistical guest+spend both exist
--    - never overwrites saved or approved Manager rows
CREATE OR REPLACE FUNCTION public.ensure_revenue_manager_target_lines_month(
  p_tenant_id uuid, p_year integer, p_month integer, p_venue_ids uuid[]
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_month_start date;
  v_month_end date;
  v_inserted integer := 0;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  IF NOT (public.is_super_admin(v_uid) OR public.is_tenant_member(p_tenant_id, v_uid)) THEN
    RAISE EXCEPTION 'Not authorized for tenant';
  END IF;
  IF NOT (public.is_super_admin(v_uid)
          OR public.has_role(v_uid,'admin'::public.app_role)
          OR public.has_role(v_uid,'manager'::public.app_role)) THEN
    RAISE EXCEPTION 'Not authorized: manager or admin role required';
  END IF;
  IF p_year < 2000 OR p_year > 2100 OR p_month < 1 OR p_month > 12 THEN
    RAISE EXCEPTION 'Invalid year/month';
  END IF;
  IF p_venue_ids IS NULL OR array_length(p_venue_ids,1) IS NULL THEN
    RAISE EXCEPTION 'venue_ids required';
  END IF;
  IF EXISTS (
    SELECT 1 FROM unnest(p_venue_ids) vid
     WHERE NOT EXISTS (SELECT 1 FROM public.venues v WHERE v.id = vid AND v.tenant_id = p_tenant_id)
  ) THEN
    RAISE EXCEPTION 'One or more venues do not belong to tenant';
  END IF;

  v_month_start := make_date(p_year, p_month, 1);
  v_month_end   := (v_month_start + INTERVAL '1 month - 1 day')::date;

  WITH stage AS (
    SELECT p_tenant_id AS tenant_id,
           v.id AS venue_id,
           sp.id AS service_period_id,
           d::date AS target_date
      FROM public.venues v
      JOIN public.venue_service_periods sp
        ON sp.venue_id = v.id
       AND sp.is_active = true
       AND sp.is_rollup_only = false   -- exclude benchmark/roll-up periods
      CROSS JOIN LATERAL generate_series(v_month_start, v_month_end, INTERVAL '1 day') AS d
     WHERE v.id = ANY(p_venue_ids)
       AND sp.effective_from <= d::date
       AND (sp.effective_to IS NULL OR sp.effective_to >= d::date)
       AND EXTRACT(DOW FROM d)::smallint = ANY(sp.applicable_weekdays)
  ), ins AS (
    INSERT INTO public.revenue_manager_target_lines (
      tenant_id, venue_id, target_date, line_type, service_period_id,
      target_input_mode, manager_guest_target, manager_spend_per_guest_target,
      manager_source, status, created_by, updated_by
    )
    SELECT s.tenant_id, s.venue_id, s.target_date, 'service_period', s.service_period_id,
           'drivers',
           st.statistical_guest_target,
           st.statistical_spend_per_guest,
           'statistical_default',
           'draft', v_uid, v_uid
      FROM stage s
      -- Only seed when reliable statistical drivers exist for THIS venue/date.
      -- Statistical rows now live on the venue's benchmark (roll-up) period,
      -- NOT on operational periods; join by (tenant, venue, date) only.
      JOIN public.revenue_statistical_targets_daily st
        ON st.tenant_id = s.tenant_id
       AND st.venue_id  = s.venue_id
       AND st.target_date = s.target_date
     WHERE st.statistical_guest_target IS NOT NULL
       AND st.statistical_spend_per_guest IS NOT NULL
       -- Only for single-period venues, i.e. exactly one operational period per venue.
       -- Multi-period venues must not receive fabricated defaults.
       AND (
         SELECT COUNT(*) FROM public.venue_service_periods sp2
          WHERE sp2.venue_id = s.venue_id AND sp2.is_active AND NOT sp2.is_rollup_only
       ) = 1
       AND NOT EXISTS (
         SELECT 1 FROM public.revenue_manager_target_lines m
          WHERE m.tenant_id = s.tenant_id
            AND m.venue_id = s.venue_id
            AND m.target_date = s.target_date
            AND m.line_type = 'service_period'
            AND m.service_period_id = s.service_period_id
       )
    RETURNING 1
  )
  SELECT COUNT(*) INTO v_inserted FROM ins;

  RETURN jsonb_build_object('ok', true, 'inserted', v_inserted);
END
$function$;
